# Generated by Django 4.2.1 on 2023-05-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Заявка ожидает решения'), ('accepted', 'Заявка принята'), ('rejected', 'Заявка отклонена')], default='pending', max_length=10),
        ),
    ]
