# Generated by Django 4.2.1 on 2023-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0004_alter_friendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Заявка ожидает решения'), ('accepted', 'Заявка принята'), ('rejected', 'Заявка отклонена')], default='pendin', max_length=10),
        ),
    ]
